### ISSUE TITLE
Use generic API for exchanges

### ISSUE THREAD

**Issue by LORDofDOOM** [sthewissen/Mynt#14]
Hi,

I want to suggest the use of a more generic API. I currently use https://github.com/jjxtra/ExchangeSharp it support almost all important Exchanges (e.g. Poloniex, Binance, Kraken...) and support Websockets.

Also I would suggest to make Azure Database optional to make it completely run on own hardware.

Thank you

**Comment by sthewissen** [comment]
Hey, thanks for having an interest in the project! Part of the exchange separation and support for multiple exchanges (adding Binance at the moment) is already being worked on in the develop branch. Running the Azure Functions part locally as a Windows service is also something that's in the works but it currently still uses the Azure Table Storage as a storage backend. Could be a future addition to also store the data in different ways.

**Comment by ASADeveloper** [comment]
Hi,
I just want to add that you could use Azure Storage Emulator on windows OS instead of Azure Table Storage. It's used for local development/testing.

For Azure Function, I would use an console app instead of the Windows Service. It is much simpler and actually more close to the Azure Function.

**Comment by LORDofDOOM** [comment]
@ASADeveloper : I know that this option exists but only on Windows... 

IMHO "standard" SQL implementation like MySQL or Postgres (SQLite is also a good option for fast deployment in e.g. docker) are the better way or a standalone program.

I understand that @sthewissen have choose it because of the app but normal databases are also simple to use in app environment with REST API.

**Comment by sthewissen** [comment]
Groundwork for this was done in the rework branch.
