### ISSUE TITLE
Multiple Quote Assets

### ISSUE THREAD

**Issue by dinckaniskan** [sthewissen/Mynt#19]
Hi Guys, I really like this project...great work! Can I suggest extending the scope of trade functionality to use multiple Quote Assets rather than just BTC where you can exclude Quote Assets you don't wish to trade with in the settings?

Also, I haven't checked in detail but is there a feature where you can send an exit market signal where the bot will perform a graceful shutdown after closing all active trades?

Cheers
D

**Comment by sthewissen** [comment]
There is currently no "panic button" that will close all active trades. The whole quote assets part can be included without all too much effort I think. Will look into adding that somewhere in the near future.

**Comment by sthewissen** [comment]
This is something that is being added in the rework branch.
