### ISSUE TITLE
Run local?

### ISSUE THREAD

**Issue by nielshenriksen** [sthewissen/Mynt#34]
I am very interested in this project but I need it to be able to run local. Is that in the roadmap?

**Comment by twixwix** [comment]
There is a windows service for local usage.

**Comment by twixwix** [comment]
In the master branch it is not possible to let it run on something else then azure table but in the rework branch you can do it on several databases. (SqlLite, SqlServer, etc.)

**Comment by sthewissen** [comment]
What Twix is saying is correct, there's a windows service / console version in the works. However, the rework branch is very much a work in progress.

**Comment by nielshenriksen** [comment]
ok thanks :)
