### ISSUE TITLE
Configuration problem

### ISSUE THREAD

**Issue by raphaelpessanha** [sthewissen/Mynt#51]
In azure cloud i can't edit configuration values like locally?
When the function is running in Azure, the configuration values are read from App Settings?
So i need to add an app setting, one by one, is it right?

**Comment by sthewissen** [comment]
Are you talking about the `develop` version? If so yes, you need to add an AppSetting in Azure Functions for each setting you want to alter. For settings that you don't set the default value as set in the appropriate `Options` class will be used.

**Comment by raphaelpessanha** [comment]
I'm using the master  version.
I put all configuration values manually, bot is running but i don't if is is working. I put TelegramBotToken and -221516272, but have  no message. There is another way to check is is running well?
![print](https://user-images.githubusercontent.com/10333471/39333007-aeee02bc-497f-11e8-878b-fd935cffc98c.png)

**Comment by sthewissen** [comment]
When running `master` you currently need to put your configuration values in the `Constants` class and the appropriate NotificationManagers.

https://github.com/sthewissen/Mynt/blob/master/functions/Mynt.Core/Constants.cs

https://github.com/sthewissen/Mynt/blob/master/functions/Mynt.Core/NotificationManagers/TelegramNotificationManager.cs

One of the reasons we're improving the experience in the `develop` branch is that it isn't the best thing in `master` right now.
