### ISSUE TITLE
Provide a buying strategy

### ISSUE THREAD

**Issue by kitcoun** [sthewissen/Mynt#54]
Anderson Strategy . Every time the price is down,2 times the Number of purchase loss

**Comment by NotSmileYou** [comment]
$18 buys 20 EOS and $17 buys 40 EOS.
-1=18*20/20-17. 0.333=(18*20+17*40)/60-17

**Comment by NotSmileYou** [comment]
-1 = 18 x 20 / 20-17。0.333 =（18 x 20 + 17 * 40）/ 60-17

**Comment by sthewissen** [comment]
I don't entirely follow how this strategy works yet. Also since the current bot only looks at candle data and has no context of previous trades at that point I'm not sure if it is possible in the current setup. I would like to hear more about it though. Perhaps you have a link to an explanation of the strategy? Most of the stuff I'm finding is related to the ProfitTrailer bot.

**Comment by NotSmileYou** [comment]
https://www.jianshu.com/p/ad4503310036

This strategy requires a lot of money

As long as there is no big floating drop, they are all profitable.

Not all historical transactions can be obtained from API?

So I'm curious about why you need to use the database

**Comment by NotSmileYou** [comment]
usd 1140


 price             Purchase quantity             Existing quantity   Surplus usd

18                        10                                        10                  960

17                        20                                         30                  620

16                        60                                         90                    0 
                                                                                            sell    1 440=16*90
.....Continue the cycle


still have a question. Is this program submitted for sale after the purchase is completed?

 Please forgive my laziness ^_ ^

**Comment by sthewissen** [comment]
> Not all historical transactions can be obtained from API?
> So I'm curious about why you need to use the database

Oh it's definitely possible. All the parts are there, just not together :)

> Is this program submitted for sale after the purchase is completed?

This question I don't quite understand, sorry :(

**Comment by NotSmileYou** [comment]
Hope to support the Huobi exchange.

This should be easy.

Update the ExchangeSharp .

Add the Huobi request API code to the market summary.(They are different)

![image](https://user-images.githubusercontent.com/38834202/39968494-2a042e62-5700-11e8-96e2-560af8270737.png)



SqlServerData cannot use the native login, and the account password must be required.

There will be bugs using SqlServerData. Maybe the reason why I run locally?

**Comment by sthewissen** [comment]
Made separate issues for those last 2 points.
