### ISSUE TITLE
Wiki Update - local installation

### ISSUE THREAD

**Issue by twixwix** [sthewissen/Mynt#67]
# Mynt.AspNetCore.Host local installation on Windows
The Core.Host will be in the near futur the first Mynt UI and will let give you visual output instead of log files. We will work hard on it to make it easy to use for everyone.

This is a step-by-step instruction for installing all the needed software for running mynt local on windows client or server with sql express and iis express. If you don't get it there is a very good youtube video which explains it maybe a little bit more detailed. [Youtube](https://www.youtube.com/watch?v=ZZfRlBMHds8)
Microsoft did also a very good article for publishing on iis you can find it here [Microsoft](https://docs.microsoft.com/de-de/aspnet/core/host-and-deploy/iis/index?view=aspnetcore-2.0&tabs=aspnetcore2x).

## Prepare solution for SQL Server
In your solution you have to change the bindings of the **Mynt.AspNetCore.Host** project.
![bindings](https://user-images.githubusercontent.com/5329006/40269221-6dca8bbc-5b7b-11e8-88e2-efbf38fb0e99.png)
![bindings2](https://user-images.githubusercontent.com/5329006/40269220-6d91d844-5b7b-11e8-8fb1-92ec2738b42e.png)

After you changed the bindings you have to change the used database in your **startup.cs**.
Remove:
`.AddSingleton<IDataStore, AzureTableStorageDataStore>()
                .AddSingleton(i => Configuration.GetSection("AzureTableStorageOptions").Get<AzureTableStorageOptions>())`

And add:
`.AddSingleton<IDataStore, SqlServerDataStore>()
                .AddSingleton(i => Configuration.GetSection("SqlServerOptions").Get<SqlServerOptions>())`

## Publishing
Since in the project is the Mynt.AspNetCore.Host you can choose between two modes.
`<TargetFrameworks>netcoreapp2.0;net471</TargetFrameworks>`

1.  To edit this you have right click on the Mynt.AspNetCore.Host project and then click on **Mynt.AspNetCore.Host edit**.

2.  Choose on of them but you can run both target frameworks on Windows. 

3.  Right click on the Mynt.AspNetCore.Host and click **Publish** (check picture 1). Select the target folder maybe you have first to create a profile which includes the target folder.
![1](https://user-images.githubusercontent.com/5329006/40143367-8107dad0-595b-11e8-9600-fed6abe250f8.png)

## Install IIS express and SQL express 
Download the latest versions from the links and install all of them. Most of the time you just can click next.. next.. next.
- [SQL Server 2017 Express-Edition](https://www.microsoft.com/de-ch/sql-server/sql-server-editions-express)
- [Microsoft SQL Server Management Studio Express ](https://www.microsoft.com/de-ch/download/details.aspx?id=8961)
- [Internetinformationsdienste (IIS) 10.0 Express](https://www.microsoft.com/de-de/download/details.aspx?id=48264)

### IIS Server
On Windows Server operating systems it is a little bit different you have to enable the Web Server (IIS) server role and establish role services.

1.  Use the Add Roles and Features wizard from the Manage menu or the link in Server Manager. On the Server Roles step, check the box for Web Server (IIS).
![server-roles-ws2016](https://user-images.githubusercontent.com/5329006/40268989-2705bfb0-5b78-11e8-9dec-4c4e655027ac.png)

2.  After the Features step, the Role services step loads for Web Server (IIS). Select the IIS role services desired or accept the default role services provided. 
![role-services-ws2016](https://user-images.githubusercontent.com/5329006/40268990-27290452-5b78-11e8-90e3-42a782507878.png)

## Install .Net Core or .Net471
It depends on what you choosed but there are the links for both of them. You just have to install what you need.
- [.Net Core](https://www.microsoft.com/net/download/thank-you/dotnet-runtime-2.0.7-windows-hosting-bundle-installer)
- [Microsoft .NET Framework 4.7.1 Developer Pack](https://www.microsoft.com/en-us/download/details.aspx?id=56119)

## Quick and dirty (Only .Net47)
You also can install it directly in windows just goto:
- Start>Control Panel>Windows features activate or deactivate
- Select **.Net Framework 4.7 Advanced Services**
- and **Internet information services**
![windowsfeatures](https://user-images.githubusercontent.com/5329006/40143369-81291362-595b-11e8-8851-a21fc6c0a26d.png)

## Create site in IIS
> As note the **physical path** has to be your folder with the publish output.

1. On the hosting system, create a folder to contain the app's published folders and files. An app's deployment layout is described in the Directory Structure topic.

2. Within the new folder, create a logs folder to hold ASP.NET Core Module stdout logs when stdout logging is enabled. If the app is deployed with a logs folder in the payload, skip this step. For instructions on how to enable MSBuild to create the logs folder automatically when the project is built locally, see the Directory structure topic.

3. In IIS Manager, open the server's node in the Connections panel. Right-click the Sites folder. Select Add Website from the contextual menu.

4. Provide a Site name and set the Physical path to the app's deployment folder. Provide the Binding configuration and create the website by selecting OK:
![add-website-ws2016](https://user-images.githubusercontent.com/5329006/40269032-a50516a4-5b78-11e8-80f9-cee0e9ef04a8.png)

> Very important if your ip is set to localhost you have to place a adress into hostname as example **mynt.bot.com** in case of this you have to edit you local host file. for this goto and open the host file.
`C:\Windows\System32\drivers\etc`
In the host file you have to add now this line.
`	127.0.0.1       mynt.bot.com`

## Prepare SQL express
Just add an empty database named as you want as example **Mynt**.

## Add Connection string to your configs
Add now the connection string in the appsettings.json
` Mynt/src/Mynt.AspNetCore.Host/appsettings.json`

It should look like this
` "SqlServerOptions": {
   "SqlServerConnectionString": "Data Source=.\\YOUR_SQL_SERVER_NAME;Initial Catalog=Mynt;Integrated Security=True;MultipleActiveResultSets=True"
  },
`
Replace **YOUR_SQL_SERVER_NAME** with your sql express server name

## Start the game
Now you can run the site in IIS just with start page. Have fun :)

## Error Solving
Just go to the log file and check the errors.  ;)

If anything is wrong or not understandable you are welcome to edit this small description.   :-)

**Comment by sthewissen** [comment]
No need to close yet, was still in the process of copy pasting stuff over ;D

**Comment by twixwix** [comment]
Oops sorry thought so I can show you that I am finish ;-)

**Comment by sthewissen** [comment]
Moved it all over.
