### ISSUE TITLE
Installation (Azure) problem

### ISSUE THREAD

**Issue by kitcoun** [sthewissen/Mynt#68]
hello

How to run a program?

![image](https://user-images.githubusercontent.com/38834202/40165364-5f8ef1fc-59ee-11e8-8957-dec26ecad061.png)

Does it depend on it?

So what do I do?

**Comment by sthewissen** [comment]
If everything is set up correctly these should run automatically. These are Timer Functions which mean that they run automatically on set intervals. The BuyTimer runs every hour and the SellTimer every minute.

**Comment by kitcoun** [comment]
![image](https://user-images.githubusercontent.com/38834202/40165842-9b27c88c-59ef-11e8-9ec0-5bb647481b7a.png)

Is there anything to fill in?

**Comment by sthewissen** [comment]
No there is not. If the Azure Functions project is correctly deployed you should be seeing this because the code is deployed in compiled form.

**Comment by kitcoun** [comment]
![image](https://user-images.githubusercontent.com/38834202/40166410-0ebeb3c2-59f1-11e8-91aa-0197228a2168.png)
I deployed the configuration file by downloading it.
--------------------------------------------------------------
Because I didn't  not (Function Apps) after the VS deployment.

**Comment by kitcoun** [comment]
Creating a new profile is no Function Apps.

**Comment by kitcoun** [comment]
![image](https://user-images.githubusercontent.com/38834202/40167234-1b05f3be-59f3-11e8-818f-14bfa3f2be26.png)


![image](https://user-images.githubusercontent.com/38834202/40167179-ee6bab64-59f2-11e8-8b8f-6353b70f6bdb.png)

Did I choose the wrong one?

**Comment by sthewissen** [comment]
Both of those WebApps are not necessary to run it. The only thing you need is the Function App. Did you also install the Azure Functions SDK? See this page for more details:

https://docs.microsoft.com/en-us/azure/azure-functions/functions-develop-vs

**Comment by kitcoun** [comment]
I create a new configuration file deployment that will become WebApps.

I'm sure I've installed it.
![image](https://user-images.githubusercontent.com/38834202/40167876-b93bc418-59f4-11e8-9bc9-a0374c02b5d0.png)

**Comment by kitcoun** [comment]
![image](https://user-images.githubusercontent.com/38834202/40168314-c3738e38-59f5-11e8-801c-07088ae98bdb.png)

**Comment by sthewissen** [comment]
You should be able to publish it using the instructions here:

https://docs.microsoft.com/en-us/azure/azure-functions/functions-develop-vs#publish-to-azure

**Comment by kitcoun** [comment]
That's how I Publish it.

Thank you.

I'll try again.

**Comment by kitcoun** [comment]
There was a problem with my Visual Studio tool,When I fix it,  can normal release it.

**Comment by kitcoun** [comment]
I How do I determine whether the Function App is normal operation?

![image](https://user-images.githubusercontent.com/38834202/40266710-c0f0f1b2-5b82-11e8-9935-ed0d5c0fffb8.png)
Where does this log look?

**Comment by sthewissen** [comment]
The log gets written to the section with the loop icon on the left side menu for your function. In English it's called **Monitor** in English.

![](https://user-images.githubusercontent.com/38834202/40165842-9b27c88c-59ef-11e8-9ec0-5bb647481b7a.png)

**Comment by kitcoun** [comment]
thank you
---------------------------------------------------
These may need to be modified.

![image](https://user-images.githubusercontent.com/38834202/40289807-1318ced6-5ced-11e8-83e6-f3b7593792b7.png)
---------------------------------------------------
API error
https://github.com/jjxtra/ExchangeSharp/issues/146
